<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
  <array>
    <string>ib</string>
    <string>ibconf</string>
  </array>
  <key>name</key>
  <string>IB</string>
  <key>patterns</key>
  <array>
    <dict>
      <key>comment</key>
      <string>keywords</string>
      <key>match</key>
      <string>\b(?:if|else|match|for)\b</string>
      <key>name</key>
      <string>keyword.control.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>constants</string>
      <key>match</key>
      <string>\b(?:true|false)\b</string>
      <key>name</key>
      <string>constant.language.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>numbers</string>
      <key>match</key>
      <string>\b\d+\.?(?:\d+)?\b</string>
      <key>name</key>
      <string>constant.numeric.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>double quoted string</string>
      <key>match</key>
      <string>\"[^\"]*\"</string>
      <key>name</key>
      <string>string.quoted.double.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>comment</string>
      <key>begin</key>
      <string>//</string>
      <key>end</key>
      <string>$</string>
      <key>name</key>
      <string>comment.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>operators</string>
      <key>match</key>
      <string>(?:=|==|\+=|-=|\+|-)</string>
      <key>name</key>
      <string>keyword.operator.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>targets</string>
      <key>match</key>
      <string>\b(?:action|copy|executable|group|shared_library|source_set|static_library)\b</string>
      <key>name</key>
      <string>entity.name.tag.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>functions</string>
      <key>match</key>
      <string>\b(?:assert|config|defined|execute|zip|unzip|download|download_and_extract|list_files|getenv|import|print|rebase_path|template)\b</string>
      <key>name</key>
      <string>entity.name.function.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>predefined variables</string>
      <key>match</key>
      <string>\b(?:target_arch|target_os|target_config|target_out_dir)\b</string>
      <key>name</key>
      <string>variable.parameter.ib</string>
    </dict>
    <dict>
      <key>comment</key>
      <string>target variables</string>
      <key>match</key>
      <string>\b(?:cflags_asm|cflags|cflags_c|cflags_cc|cflags_objc|cflags_objcc|ldflags|configs|data|data_deps|defines|depfile|deps|on_init|on_pre_build|on_post_build|include_dirs|frameworks|lib_dirs|libs|output_extension|output_name|outputs|public|public_configs|public_deps|script|sources|testonly|visibility|contents|output_conversion|rebase|data_keys|walk_keys)\b</string>
      <key>name</key>
      <string>entity.other.attribute-name.ib</string>
    </dict>
  </array>
  <key>scopeName</key>
  <string>source.ib</string>
  <key>uuid</key>
  <string>DE419E8C-EC46-4814-87F3-732AD08604DC</string>
</dict>
</plist>
